# -*- coding: utf-8 -*-
"""tugas_12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSstYxRypMd-cvvjj5amL4kmrCF-S-pX
"""

print("a. Luas persegi panjang\n")
def luas_persegi(panjang = int(input('Masukkan panjang: ')), lebar = int(input('Masukkan lebar: '))):
  luaspersegi = panjang * lebar
  return luaspersegi

print(f'Hasil luas persegi panjang adalah: {luas_persegi()}\n')

print("b. Volume persegi panjang\n")
def volume_persegi(panjang = int(input('Masukkan panjang: ')), lebar = int(input('Masukkan lebar: ')), tinggi = int(input('Masukkan tinggi: '))):
  volumepersegi = panjang * lebar * tinggi
  return volumepersegi

print(f'Hasil volume persegi panjang adalah: {volume_persegi()}\n')

print("c. Luas lingkaran\n")
def luas_lingkaran(jari = float(input('Masukkan jari-jari lingkaran: '))):
  phi = 3.14
  luas = phi * (jari ** 2)
  return luas

print(f'Hasil luas lingkaran adalah: {luas_lingkaran()}\n')

print("d. Volume bola\n")
def volume_bola(jari = float(input('Masukkan jari-jari bola: '))):
  phi = 3.14
  volume = (4/3) * phi * (jari ** 3)
  return volume

print(f'Hasil volume bola adalah: {volume_bola()}\n')

