# -*- coding: utf-8 -*-
"""Tugas 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkkz_UinlWa4lrepbCKbHaH2sDsqvMFJ

1. Tuples

a. Buat sebuah tuple bernama mahasiswa yang berisi data diri anda dengan 3 nilai:
(“Nama”, “NIM”,”Prodi”)

b. Tampilkan data NIM dan Prodi
"""

#a
print("a.")
dataDiri = ("Dany", 2505060062, "S1 Teknologi Informasi")
print(f'Nama\t: {dataDiri[0]}\nNIM\t: {dataDiri[1]}\nProdi\t: {dataDiri[2]}\n')
#b
print("b.")
print(dataDiri[1])
print(dataDiri[2])

"""2. Dictionary

a. Buat dictionary keranjang dengan data: {"apel": 5000, "pisang": 3000, "jeruk": 7000,
"anggur": 15000}

b. Gunakan perulangan untuk menghitung total harga semua barang

c. Tampilkan setiap barang dan harganya dalam format: ex: "Harga apel: Rp
5000"

d. Tampilkan harga total belanja
"""

keranjang = {
    "Apel":5000,
    "Pisang":3000,
    "Jeruk":7000,
    "Anggur":15000,
}
perulangan = 0
total = 0
for buah, harga in keranjang.items():
  # perulangan += 1
  # print(f'perulangan ke {perulangan}')
  print(f'Harga {buah}\t: Rp {harga}')
  total += harga
print(f'Total Harga\t: Rp {total}\n')

